GET http://localhost:7000 HTTP/1.1
###
POST http://localhost:7000/api/users/register
Content-Type: application/json

{
    "username" : "johndoe",
    "firstName": "John",
    "lastName": "Doe",
    "email": "johndoe@gmail.com",
    "password": "john_pw"
}

###
POST http://localhost:7000/api/users/register
Content-Type: application/json

{
    "username" : "abdulghani",
    "firstName": "Abdul",
    "lastName": "Ghani",
    "email": "abdulghani@gmail.com",
    "password": "abdul_pw"
}

### Login
POST http://localhost:7000/api/users/login
Content-Type: application/json 

###
GET http://localhost:7000/

###
GET http://localhost:7000/dashboard/

### API Test post
GET http://localhost:7000/api/posts